import { Stack, Box, Grid, Divider } from "@mui/material";
import { useZTheme } from "../../../stores/useZTheme";
import { useTranslation } from "react-i18next";
import { useZMspRegisterPage } from "../../../stores/useZMspRegisterPage";
import { InputLabelTooltip } from "../../../components/Inputs/InputLabelTooltip";
import { InputUploadLabelTooltip } from "../../../components/Inputs/InputUploadLabelTooltip";
import { TextRob16Font1S } from "../../../components/Text1S";
import { TextRob16FontL } from "../../../components/TextL";

export const MspFormStep2 = () => {
  const { theme, mode } = useZTheme();
  const { t } = useTranslation();
  const {
    mspDomain,
    setMSPDomain,
    admName,
    setAdmName,
    admEmail,
    setAdmEmail,
    admPhone,
    setAdmPhone,
    position,
    setPosition,
    setBrandLogo,
    brandLogoUrl,
  } = useZMspRegisterPage();

  return (
    <Stack
      sx={{
        width: "100%",
        gap: "32px",
      }}
    >
      <Box>
        <TextRob16FontL
          sx={{
            color: theme[mode].primary,
            fontSize: "20px",
            fontWeight: 600,
            marginBottom: "16px",
          }}
        >
          {t("mspRegister.mspDomain")}
        </TextRob16FontL>
        <InputLabelTooltip
          label={
            <>
              {t("mspRegister.domain")}{" "}
              <span style={{ color: theme[mode].danger }}>
                {t("mspRegister.required")}
              </span>
            </>
          }
          value={mspDomain}
          onChange={setMSPDomain}
          placeholder="XX.XXX.XXX"
        />
      </Box>

      <Box>
        <TextRob16FontL
          sx={{
            color: theme[mode].primary,
            fontSize: "20px",
            fontWeight: 600,
            marginBottom: "16px",
          }}
        >
          {t("mspRegister.principalAdmin")}
        </TextRob16FontL>

        <Grid container spacing={3}>
          <Grid item xs={12} md={6}>
            <InputLabelTooltip
              label={
                <>
                  {t("mspRegister.completeName")}{" "}
                  <span style={{ color: theme[mode].danger }}>
                    {t("mspRegister.required")}
                  </span>
                </>
              }
              value={admName}
              onChange={setAdmName}
              placeholder={t("mspRegister.completeNamePlaceholder")}
            />
          </Grid>
          <Grid item xs={12} md={6}>
            <InputLabelTooltip
              label={
                <>
                  {t("mspRegister.email")}{" "}
                  <span style={{ color: theme[mode].danger }}>
                    {t("mspRegister.required")}
                  </span>
                </>
              }
              value={admEmail}
              onChange={setAdmEmail}
              placeholder={t("mspRegister.emailPlaceholder")}
              type="email"
            />
          </Grid>

          <Grid item xs={12} md={6}>
            <InputLabelTooltip
              label={t("mspRegister.phone")}
              value={admPhone}
              onChange={setAdmPhone}
              placeholder="(00) 00000-0000"
            />
          </Grid>
          <Grid item xs={12} md={6}>
            <InputLabelTooltip
              label={t("mspRegister.position")}
              value={position}
              onChange={setPosition}
              placeholder={t("mspRegister.positionPlaceholder")}
              disabled={true}
            />
          </Grid>

          <Grid item xs={12} md={6}>
            <Box>
              <InputLabelTooltip
                label={t("mspRegister.initialPassword")}
                value=""
                onChange={() => {}}
                placeholder={t("mspRegister.initialPasswordPlaceholder")}
                type="password"
                disabled={true}
              />
              <TextRob16Font1S
                sx={{
                  color: theme[mode].gray,
                  fontSize: "12px",
                  marginTop: "4px",
                  fontStyle: "italic",
                }}
              >
                {t("mspRegister.passwordAutoGenerated") ||
                  "A senha será gerada automaticamente"}
              </TextRob16Font1S>
            </Box>
          </Grid>
          <Grid item xs={12} md={6}>
            <InputLabelTooltip
              label={t("mspRegister.username") || "Nome de Usuário"}
              value={""}
              onChange={() => {}}
              placeholder={t("mspRegister.username") || "Nome de Usuário"}
              disabled={true}
            />
          </Grid>
        </Grid>
      </Box>

      <Divider sx={{ borderColor: theme[mode].gray }} />

      <Box>
        <TextRob16FontL
          sx={{
            color: theme[mode].primary,
            fontSize: "20px",
            fontWeight: 600,
            marginBottom: "8px",
          }}
        >
          {t("mspRegister.companyLogo")}
        </TextRob16FontL>
        <TextRob16Font1S
          sx={{
            color: theme[mode].gray,
            fontSize: "14px",
            marginBottom: "16px",
          }}
        >
          {t("mspRegister.companyLogoSubtitle")}
        </TextRob16Font1S>

        <Grid container spacing={3}>
          <Grid item xs={12} md={6}>
            <InputUploadLabelTooltip
              label=""
              toolTipMessage=""
              onUploaded={({ url, objectName }) =>
                setBrandLogo({ brandLogoUrl: url, brandObjectName: objectName })
              }
              disabled={false}
              sxContainer={{
                maxWidth: "400px",
              }}
            />
          </Grid>
          {brandLogoUrl && (
            <Grid item xs={12} md={6}>
              <Box
                sx={{
                  display: "flex",
                  flexDirection: "column",
                  gap: "8px",
                  alignItems: "flex-start",
                }}
              >
                <Box
                  sx={{
                    width: "165px",
                    height: "50px",
                    border: `1px solid ${theme[mode].gray}`,
                    borderRadius: "8px",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    background: theme[mode].mainBackground,
                  }}
                >
                  <img
                    src={brandLogoUrl}
                    alt="Logo"
                    style={{ maxWidth: "100%", maxHeight: "100%" }}
                  />
                </Box>
                <Box sx={{ display: "flex", gap: "16px" }}>
                  <Box
                    onClick={() => {
                      setBrandLogo({ brandLogoUrl: "", brandObjectName: "" });
                    }}
                    sx={{
                      cursor: "pointer",
                      "&:hover": { opacity: 0.8 },
                    }}
                  >
                    <TextRob16Font1S
                      sx={{
                        color: theme[mode].blue,
                        fontSize: "14px",
                      }}
                    >
                      {t("mspRegister.changeLogo") || "Alterar logo"}
                    </TextRob16Font1S>
                  </Box>
                  <Box
                    onClick={() => {
                      setBrandLogo({ brandLogoUrl: "", brandObjectName: "" });
                    }}
                    sx={{
                      cursor: "pointer",
                      "&:hover": { opacity: 0.8 },
                    }}
                  >
                    <TextRob16Font1S
                      sx={{
                        color: theme[mode].danger,
                        fontSize: "14px",
                      }}
                    >
                      {t("mspRegister.removeLogo") || "Remover logo"}
                    </TextRob16Font1S>
                  </Box>
                </Box>
                <Box sx={{ marginTop: "8px" }}>
                  <TextRob16Font1S
                    sx={{ color: theme[mode].gray, fontSize: "12px" }}
                  >
                    {t("mspRegister.logoStandard") || "Padrão: 165x50px"}
                  </TextRob16Font1S>
                  <br />
                  <TextRob16Font1S
                    sx={{ color: theme[mode].gray, fontSize: "12px" }}
                  >
                    {t("mspRegister.logoSize") || "Tamanho: 50mb"}
                  </TextRob16Font1S>
                  <br />
                  <TextRob16Font1S
                    sx={{ color: theme[mode].gray, fontSize: "12px" }}
                  >
                    {t("mspRegister.logoFormats") ||
                      "Formatos: .svg .png .jpg .gif .webp"}
                  </TextRob16Font1S>
                </Box>
              </Box>
            </Grid>
          )}
        </Grid>
      </Box>
    </Stack>
  );
};
